language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - cd pytorch
  - cd vsl-extension
  - python setup.py install
  - cd ..
  - cd ..
script:
  - pytest
